### PR TITLE
Add post about automation rules

### PR DESCRIPTION
**Pull request by stsewd**
Tried to keep it small.

We need to merge https://github.com/readthedocs/blog/pull/77 first

### CODE REVIEW

**Comment by ericholscher** [comment]
We should ship this soon.

**Comment by ericholscher** [comment]
@stsewd anything needed here before shipping? I think it would be useful to do 👍

**Comment by stsewd** [comment]
@ericholscher nothing else, I can update the date for today if you want to ship it now

**Comment by ericholscher** [comment]
We just shipped the conda one, so lets hold off for a couple days, but 👍 on shipping it soon

**Comment by ericholscher** [comment]
@stsewd I'm happy to ship this today 👍

**Comment by ericholscher** [comment]
@stsewd Want to put a proposed tweet in the description and we'll use that when we ship it?

**Comment by stsewd** [comment]
@ericholscher hope this is fine :eyes: 

>  A time ago we introduced a feature to help users to automate some tasks over new versions 🤖. Learn more about it at <link>. Let us know what other tasks you would like to automate!

**Comment by ericholscher** [comment]
Shipping 👍

**Pull request merged**
