### PR TITLE
Add sphinxext-opengraph

### LINKED ISSUE #108: Adopt `sphinxext-opengraph`
@humitos pointed me out to https://github.com/wpilibsuite/sphinxext-opengraph/, which would be interesting to test across RTD [as we noted](https://github.com/readthedocs/readthedocs.org/issues/1758#issuecomment-793200657). I think a good first place to add it would be our blog, since we usually share posts on social media, and having OpenGraph tags would make them look nicer with little effort, in principle.

However, we are using an ancient version of Sphinx in our blog, and the extension requires Sphinx 2.0 or greater. Therefore, we would need to upgrade it first. Therefore, this is blocked on #107.

### PR DESCRIPTION
**Pull request by astrojuanlu**
This should improve the appearance of our links when shared in social media. Close #108.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
The generated image link is wrong: `background-image: url("https://readthedocs-blog--118.org.readthedocs.build../_images/rebuild.png");` will open an issue upstream about this.

**Comment by astrojuanlu** [comment]
https://github.com/wpilibsuite/sphinxext-opengraph/issues/43

**Comment by astrojuanlu** [comment]
- Before: https://www.opengraph.xyz/url/https%3A%2F%2Fblog.readthedocs.com%2Fnewsletter-july-2021%2F/
- After: https://www.opengraph.xyz/url/https%3A%2F%2Freadthedocs-blog--118.org.readthedocs.build%2Fnewsletter-july-2021%2F/

Some caveats:

- I used the "Dark color logo and wordmark for use on light colors" from https://docs.ops.verbthenouns.com/projects/guidelines/branding.html but it doesn't quite fit the aspect ratio of media shares
- I can't test Twitter Cards in this pull request because `robots.txt` disallows indexing

**Comment by humitos** [comment]
> but it doesn't quite fit the aspect ratio of media shares

I don't like how it looks 😄 

What about using just the logo, https://docs.ops.verbthenouns.com/projects/guidelines/_downloads/ed58d5ce6820efcfb0aa0146ee561409/logo-dark.png 

Another option is to update the same image that you are using but with a bigger height (blank) so it scales properly.

**Comment by astrojuanlu** [comment]
> I don't like how it looks 😄 

Yeah, me neither 😂 testing your proposal

**Comment by astrojuanlu** [comment]
Better now (at least the text is not cut)

Screenshot from 2021-07-22 10-42-48

For anything more sophisticated than this, I'd need to refresh my GNU I.M.P. abilities :)

**Comment by nienn** [comment]
It's greatly improved. Although  I still don't like the look of the oversized logo 😄 

Based on [this article](https://iamturns.com/open-graph-image-size/) the best image size should be 1200 x 630.


> I'd need to refresh my GNU I.M.P. abilities :)

I can alter the image if there's an option to upload it somewhere.

**Comment by astrojuanlu** [comment]
Super insightful article, thanks @nienn !

> I can alter the image if there's an option to upload it somewhere.

In the absence of a better option, I guess we can upload it to the blog itself?

**Comment by humitos** [comment]
> In the absence of a better option, I guess we can upload it to the blog itself?

Sounds good to me!

**Comment by astrojuanlu** [comment]
@nienn sent me a modified version of the logo, modified from the original SVG for a more appropriate aspect ratio (thanks!). However, as I added it as part of this PR, I won't be able to test it until it's merged.

**Comment by nienn** [comment]
test

This is NOT a real test on [opengraph.xyz](https://www.opengraph.xyz). It's just a montage with a preview of what it should look like.

**Comment by astrojuanlu** [comment]
It looks great! When someone submits an accepting ✔️ 🟢  review I will merge the pull request, and we can make further adjustments thereafter

**Comment by ericholscher** [comment]
@nienn Looks great -- I'll let @agjohnson chime in as current owner of the brand, but I'm guessing that might shift to you here before long ✨

**Comment by agjohnson** [comment]
Looks good! The wordmark doesn't lend great to being split up, with the italicized `the` in the middle, but I don't think that's a huge issue given the use case here.

Two options that would preserve the wordmark/logo for this format would be logo or wordmark only, but in the correct ratio, or logo in the background (probably fade out a good deal) and the main, single line wordmark centered overlaying that.

All seem like good options.

**Comment by agjohnson** [comment]
Also, this image format would be great to include in guidelines repo.

**Comment by nienn** [comment]
Moving the logo discussion over here: [readthedocs/guidelines](https://github.com/readthedocs/guidelines/issues/1#issue-950955755)

So it won't keep blocking this PR!

**Comment by astrojuanlu** [comment]
I get from the discussion that this is a good start, and that there will be possibly more iterations on https://github.com/readthedocs/guidelines/issues/1, so I'll go ahead and merge this, so we can start testing how it looks like in real life. Thanks everyone!

**Comment by astrojuanlu** [comment]
Just tested it, it works 💯

**Pull request merged**
